[package]
name = "kixdns-panel-helper"
version = "1.0.6"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rustix = { version = "1.1.4", features = ["fs", "net", "std"] }

[lints]
workspace = true
